sudo: false

language: c++

dist: xenial

compiler:
￼  - g++
￼  - clang

script:
    - ./presubmit.sh || travis_terminate 1

#   - cmake -DUSE_SDL=ON -DUSE_RLGLUE=OFF -DBUILD_EXAMPLES=ON
    - cmake -DUSE_SDL=OFF -DUSE_RLGLUE=OFF -DBUILD_EXAMPLES=OFF
    - make -j 4
