name: Release ale-py

on:
  release:
    types: [published]

jobs:
  release:
    name: Release ale-py
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/download-release-asset
      name: Download ale-py release asset
      with:
        filename: ale-py.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Unzip ale-py asset
      run: |
        unzip ale-py.zip -d dist
    - name: Publish to PyPi
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.pypi_token }}
